# Este archivo es SOLO para referencia de la estructura.

services:
  # En Producción: PostgreSQL Managed Database
  db:
    image: postgres:15-alpine

  # En Producción: Servicio Docker individual
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

  # En Producción: Servicio Docker individual
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
